# Generated by Django 5.0.3 on 2024-03-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('PatientFirstName', models.CharField(max_length=500)),
                ('PatientLastName', models.CharField(max_length=500)),
                ('PatientBirthdate', models.IntegerField(max_length=8)),
            ],
        ),
    ]
