# Generated by Django 5.0.3 on 2024-03-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientChart', '0003_patient_delete_patients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
